version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.3.1-stretch
    steps:
      - checkout
      - run: npm ci
      - run: npm run build-gh
      - run: npx ngh --repo=https://$GHPAGES_DEPLOY_KEY@github.com/tkglaser/app-nehmen.git --name="Thomas Glaser" --email=thomas@tkglaser.net
workflows:
    version: 2
    main:
        jobs:
            - build:
                filters:
                    branches:
                        only: master
